/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsPowerRouteImport } from './routes/us-power'
import { Route as UsGasRouteImport } from './routes/us-gas'
import { Route as SpreadsRouteImport } from './routes/spreads'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PowerRouteImport } from './routes/power'
import { Route as ImbalanceRouteImport } from './routes/imbalance'
import { Route as GenerationRouteImport } from './routes/generation'
import { Route as GasRouteImport } from './routes/gas'
import { Route as IndexRouteImport } from './routes/index'

const UsPowerRoute = UsPowerRouteImport.update({
  id: '/us-power',
  path: '/us-power',
  getParentRoute: () => rootRouteImport,
} as any)
const UsGasRoute = UsGasRouteImport.update({
  id: '/us-gas',
  path: '/us-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const SpreadsRoute = SpreadsRouteImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const ImbalanceRoute = ImbalanceRouteImport.update({
  id: '/imbalance',
  path: '/imbalance',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationRoute = GenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => rootRouteImport,
} as any)
const GasRoute = GasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/generation': typeof GenerationRoute
  '/imbalance': typeof ImbalanceRoute
  '/power': typeof PowerRoute
  '/prices': typeof PricesRoute
  '/spreads': typeof SpreadsRoute
  '/us-gas': typeof UsGasRoute
  '/us-power': typeof UsPowerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/generation': typeof GenerationRoute
  '/imbalance': typeof ImbalanceRoute
  '/power': typeof PowerRoute
  '/prices': typeof PricesRoute
  '/spreads': typeof SpreadsRoute
  '/us-gas': typeof UsGasRoute
  '/us-power': typeof UsPowerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gas': typeof GasRoute
  '/generation': typeof GenerationRoute
  '/imbalance': typeof ImbalanceRoute
  '/power': typeof PowerRoute
  '/prices': typeof PricesRoute
  '/spreads': typeof SpreadsRoute
  '/us-gas': typeof UsGasRoute
  '/us-power': typeof UsPowerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gas'
    | '/generation'
    | '/imbalance'
    | '/power'
    | '/prices'
    | '/spreads'
    | '/us-gas'
    | '/us-power'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gas'
    | '/generation'
    | '/imbalance'
    | '/power'
    | '/prices'
    | '/spreads'
    | '/us-gas'
    | '/us-power'
  id:
    | '__root__'
    | '/'
    | '/gas'
    | '/generation'
    | '/imbalance'
    | '/power'
    | '/prices'
    | '/spreads'
    | '/us-gas'
    | '/us-power'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GasRoute: typeof GasRoute
  GenerationRoute: typeof GenerationRoute
  ImbalanceRoute: typeof ImbalanceRoute
  PowerRoute: typeof PowerRoute
  PricesRoute: typeof PricesRoute
  SpreadsRoute: typeof SpreadsRoute
  UsGasRoute: typeof UsGasRoute
  UsPowerRoute: typeof UsPowerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/us-power': {
      id: '/us-power'
      path: '/us-power'
      fullPath: '/us-power'
      preLoaderRoute: typeof UsPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-gas': {
      id: '/us-gas'
      path: '/us-gas'
      fullPath: '/us-gas'
      preLoaderRoute: typeof UsGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imbalance': {
      id: '/imbalance'
      path: '/imbalance'
      fullPath: '/imbalance'
      preLoaderRoute: typeof ImbalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation': {
      id: '/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof GenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas': {
      id: '/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof GasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GasRoute: GasRoute,
  GenerationRoute: GenerationRoute,
  ImbalanceRoute: ImbalanceRoute,
  PowerRoute: PowerRoute,
  PricesRoute: PricesRoute,
  SpreadsRoute: SpreadsRoute,
  UsGasRoute: UsGasRoute,
  UsPowerRoute: UsPowerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
